language: node_js
node_js:
  - 6.9.2
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - CXX=g++-4.8
addons:
  ssh_known_hosts: thomasconroy.net
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
- bash _scripts/install.sh
script:
  - bash _scripts/build.sh
  - bash _scripts/test.sh
after_success:
  - bash _scripts/deploy.sh
