language: node_js
node_js:
  - 6.9.2
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - CXX=g++-4.8
  - secure: "hPedILdIQ9RqR+7kQMyKH7F31oTTMp+SXzsA2df+Tb/PPC8365WKPC5PeLt4/RP17R1lexp5yBcHqCirdI4gFS1hfXy1t94Xwo0l7JBWHCLcBRDBlVoHN/1EyTcOYmbA8Im6ri4fvdFtxHSOC07Xolytyc4vM7Brp7bz1G4JwPICJ3Vrff94iSH71AH3hOJqFKL9cZAaV5PuA1hi1Fs2Dwg299lExJeWr3Npua224QvOB/IHtPp3+IxT/Atw+n5T+xg0Rs+ED9hIe5K+XzA9NGnV6FkJrsUoLE7bjAdzoZBdkzNIozW5NGJcZjvJ8H1rBSd/vYxYTXcnzaGM6BjUDPTRYR7E5PWHL645eWlwlwPhbpBpdTVZ13oXVpJHEBnY8qNQWyhJX2lhXZoTZSFm+kkACaGF3UNFcxyGfSSGx4pJe4JXZs22MKCqls7Qt6gUZTZiwMOS2NsbLu5ZBCicy7rcS5zwaoKz/B9/sHeKEXx+fyZbkVEIz/qiPMfbQH+t4HGm05UIJJJUf/bpYMITbJ5sVnDlJ98nvZVEa6DARgsH8fF9GHagcTDeScv6PYefgVwaQyA8Cb8ovzYRhRO8f2oQ9WwwPddWNOKdpqTAnUE2twDx1Q33RPX7norwRnT6nvFl9mLN929O/WqVJ65qMN+QvjCjafB0RP/Dbh4AFQ8="
  - secure: "Yt0JoNpKyiud0kz4uoiENXvIpIkQ5HRTWRcrzuIcTPuvoSmpI/DLkxylN2yKh2ccnnwga6BkwoScvyPlhu3WZZLk4VAoM3xXAqNUMJHMLU6/7uclJOKKb0tipoRw9OBUrmyHf+vxorqHlkxV8j22bnYNo3AoX3zRB/seCjgSV3SVvIH5tdn+/KT5X/YzP5FUw/MvY8xsjKWoMLV74EbcHI6BSUcyuejFLKSZBiHrZzYxrxaLH3fykfA7LgXPhcSCFaZyJHR2wgMiuXaDZGH1URZzYH0mMa2ffx3sFEgfa6Yl65RLHAgVt7AITkUMrVwTD0XYIdOzjjMxORERihCUNTNdQVOM8EO7TEF5OEmPZHQhaTv2SDIk6JGmKDQZtTFfrZobDnuL0F5lKTiaq1fb5kLNYssvkmlgCahsBlaF+KRI5oMntyS7B2PwAAFcJspud2eKlBPrVCFx43t/pjyJ6y5iGAxsOsxC07E+zZjclP1vLvpt+ZSiR49GgQ+dqoBApZ89KnycZIFiQytByljE+aOb5dHOVS1sFrxaa6+olIK+PQKo8/1TPGUboQj51aipU7Jn4XwVNBtVhUNSHt3vC1j0GnyRllmdvTeWodr/2rpnVFCPn/31RE9AqN/ffPgqqWQO959h1sPrbRiYLzsFfww1J0iYojlfMw7QFlenVO4="
  - secure: "Zc0vVsAM3ZkgZdoM2SBwNdiSCU1CMN36zwH9fDSy/xl++8oPGMCQsVUlyyEX+d3643DXCefwkcBzvQAEyRQBsG6Lovdl5ntKssf3OH9682K6ieg5qB4QV/wh/LDGheMqbYwOp8tIN0YLoCdRgCFZnO9us7y7Ffdbqal4Ubo5MgCpgD1AAWGrImDwysC0JWkkXEpvkcmFUlLlkOEh5MloZ3/c2lc7vkV8LmogIRzJqEXO6IDdNcZ7dFcW4jzJegGrH4EPclIBrLWbv4E7XgtNITBAI1njkP5O5r/OBZnbzl79lAaOENLRXUBWabT3LdA8LIEpqafc0igbH8Tiyc9X0tb5poSFr5cGDtpmB/kHgQVtMG7h6C/zjsnm4S+nnypOs6kNrrZmqW0CWA9jHNuKXqKYwYRelPjXK0lkcckKaFg7/GdRUfCu76FCQP0OgTBUrXZhe9nUpbAoHMvn1pBjj32SVHat1swhEWkCQPpv9IdPLRffenkvuAFZioZ1coX+e8udUzs4vMpl7AZBmIKBpoc9+qYQ+jEtWfqzatmNEWTpmcCQ62reiQuHwvQLDk6PcqkFpHLP9ls9Q3xoKNO7H4MaE9WuBL3tJ7ty7+H0h7/XyEapbgj7wFiFbA3vjjeoo1nbb50fAUpP/y0oxCj4W0TvTN5LsRigRotzTNNYIbw="
  - secure: "jSape/RjjMXnG3OPQyeregzvjo2jp+R/KX61WRr7rJ5hoRKPHink2KwqYCfmY821aWIlTOCbxyflrKV7RLmc5svp7ZrPJUg6egE13F4FafDArpjCupb/bFHjN3KFdukrPM2uth+b1MmBGrViwwlUlIgAWiNQ6yKIGFOPxvbMegvC90DUWf9briH1ICVLsNHQf59d6Yg3vYsP7xNNSF1qV2viXE/q+yzLZZ/9rhzv3Ox/3ZrcS/a5S9T8pTbL51DcR3vOrELNWqB27FZLhUOzVgoNxslE7qvztgTX8fav133fgT9S1UniNpJdPW7xffUbSQ6dsEAmN9lLaXCdXTCvJF/jWuSYIJeDQHwDVNX8o30vuvwTtYeuUXpvAUPnWzkKkALB0wPGWDfh0FL6MB1LXNeLaC+znEJFuUKwI6uZqNsZxQOFtRWGvmjEAWlqKBl103kM5eIkDmwVqKqsFeVhiPSPQnikcl4bw/nxwWBC2cMz8dOvIHScoCRMRWDGmN6Ah4rFh7VFnV5+fY03zQ1nd51Ts5vS8uz3p5l1OtDk9/jTedorL18DhJCx3oW+mNFkzaO7RwHtLGyXvu42eX3gi2YMQy+S/2Akqf2KsqGXbD45X4uVsvvWh092r1N5U3ivBzqb7Wrjygb2FBbuCX1GFa5U5CJX7vQA17ed4eq3ZGo="
addons:
  ssh_known_hosts:
    - thomasconroy.net
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
- bash _scripts/install.sh
script:
  - bash _scripts/build.sh
  - bash _scripts/test.sh
after_success:
  - bash _scripts/deploy.sh
