name: Development Wokflow - test, linting, QA

on:
  push:
    branches-ignore:
      - master

jobs:
  install:
    name: Setup & Install Dependencies
    # should match production server.
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: bahmutov/npm-install@v1
  
  lint:
    runs-on: ubuntu-latest
    name: Run linters
    needs: [install]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: bahmutov/npm-install@v1
      - run: npm run type-check
      - run: npm run lint
      - run: npm run stylelint

  build:
    runs-on: ubuntu-latest
    name: Build
    needs: [install]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: bahmutov/npm-install@v1
      - run: npm run build-prod

  test:
    runs-on: ubuntu-latest
    name: Run Tests
    needs: [install]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: bahmutov/npm-install@v1
      - run: npm test