name: Development Wokflow - test, linting, QA

on: push

jobs:
  install-job:
    name: Configure Environment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Node Modules
        uses: actions/cache@v2
        id: cache-step
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Node.js dependencies
        if: steps.cache-step.outputs.cache-hit != 'true'
        run: npm ci

  run-linters-job:
    name: Lint
    runs-on: ubuntu-latest
    needs: [install-job]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Retrieve Node Modules cache
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Run type checker
        run: npm run type-check
      - name: Run script linting
        run: npm run lint
      - name: Run style linting
        run: npm run stylelint

  run-tests-job:
    name: Test
    runs-on: ubuntu-latest
    needs: [install-job]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Retrieve Node Modules cache
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Run unit tests
        run: npm test