name: Production Workflow - Build and Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Deploy (using cached modules)
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install Node.js dependencies
      if: steps.cache-step.outputs.cache-hit != 'true'
      run: npm ci
    - name: Build
      env:
        NEXT_TELEMETRY_DISABLED: true
      run: npm run build-prod --if-present
    - name: Reload PM2
      run: pm2 reload next-js