name: Production Workflow - Build and Deploy

on:
  push:
    branches: [ master ]

jobs:
  build_and_deploy:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Use NextJS Build cache
      uses: actions/cache@v2
      with:
        path: ${{ github.workspace }}/.next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}

    - name: Use node_modules cache
      uses: bahmutov/npm-install@v1

    - name: Build
      env:
        NEXT_TELEMETRY_DISABLED: true
        # NODE_OPTIONS: --max_old_space_size=4096
      run: npm run build-prod --if-present
    - name: Reload PM2
      run: pm2 reload next-js